// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krbozjbwfsqliltwpbhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyYm96amJ3ZnNxbGlsdHdwYmh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDU3MTIsImV4cCI6MjA3MTE4MTcxMn0.yN2iyqdQrMOZ3bLFqZW34J0pmjFh-0m0AA_mOxyRyik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});